const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'})


const doc = {
    info: {
        version: "1.0.0",
        title: "Demo Project - Open Api",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module. OAS3 tag above signifies the oas version.",
        contact: {
            email: "vishalrastogi@sharechat.co"
          }
    },
    externalDocs: {
        description: "Find out more about OAS",
        url: "https://swagger.io/specification/"
      },
      servers: [
        {
          url: "http://{username}:{port}/{basePath}",
          description: "The API server",
          variables: {
            username: {
              default: "localhost",
              description: "this value is assigned by the service provider"
            },
            port: {
              enum: [
                "8443",
                "443",
                "3000"
              ],
              default: "3000"
            },
            basePath: {
              default: ""
            }
          }
        }
      ],
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoint to interact with User"
            
        }
    ],
    securityDefinitions: {
        apiKeyAuth:{
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "X-API-KEY",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    definitions: {
        Parents: {
            father: "Simon Doe",
            mother: "Marie Doe"
        },
        User: {
            id: "100",
            name: "Jhon Doe",
            age: 29,
            parents: {
                $ref: '#/definitions/Parents'
            },
            diplomas: [
                {
                    school: "XYZ University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company"
                    }
                }
            ]
        },
        AddUser: {
            $id: "100",
            $name: "Jhon Doe",
            $age: 29,
            about: ""
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./src/index.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/index')           //project's root file
})